server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # Gateway will hit this URL to download Keycloak's public key to verify tokens locally
          issuer-uri: http://keycloak:8080/realms/hexa-medplus
  cloud:
    gateway:
      httpclient:
        connect-timeout: 120000
        response-timeout: 120s
      routes:
        - id: clinical-service
          uri: http://clinical-service:8081
          predicates:
            - Path=/api/patients/**, /api/encounters/**, /api/notes/**, /api/analytics/**, /api/clinical/**
        - id: document-service
          uri: http://document-service:8082
          predicates:
            - Path=/api/documents/**
        - id: ai-service
          uri: http://ai-service:8083
          predicates:
            - Path=/api/ai/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "${CORS_EXTRA_ORIGIN:http://localhost:3000}"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true