server:
  port: 8081

spring:
  application:
    name: clinical-service
  datasource:
    url: jdbc:postgresql://postgres:5432/hexa_medplus_db
    username: hexa_admin
    password: hexa_secure_2024
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      # INSTRUCTS JPA TO AUTO-CREATE TABLES
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer