export const DOCUMENT_STATUSES = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  REQUIRES_VERIFICATION: "REQUIRES_VERIFICATION",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const CODE_STATUSES = {
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const ENCOUNTER_STATUSES = {
  DRAFT: "DRAFT",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  SIGNED: "SIGNED",
};

export const AUDIT_ACTION_TYPES = {
  AI_GENERATED: "AI_GENERATED",
  USER_APPROVED: "USER_APPROVED",
  USER_REJECTED: "USER_REJECTED",
  USER_MODIFIED: "USER_MODIFIED",
  VIEWED: "VIEWED",
};
