server:
  port: 8082
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/hexaware
    username: postgres
    password: MSpostgres@1
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket-name: clinical-documents

document-service:
  public-url: http://localhost:8082
